@ASP_NET_11._TaskFlow__Pagination_Filtering_Ordering__HostAddress = http://localhost:5064

GET {{ASP_NET_11._TaskFlow__Pagination_Filtering_Ordering__HostAddress}}/weatherforecast/
Accept: application/json

###
