@ASP_NET_13._TaskFLow_Authentication_and_Authorization_HostAddress = http://localhost:5296

GET {{ASP_NET_13._TaskFLow_Authentication_and_Authorization_HostAddress}}/weatherforecast/
Accept: application/json

###
