@ASP_NET_12._TaskFlow_Validation_Global_exception_handler_HostAddress = http://localhost:5049

GET {{ASP_NET_12._TaskFlow_Validation_Global_exception_handler_HostAddress}}/weatherforecast/
Accept: application/json

###
